# Generated by Django 2.1.4 on 2018-12-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEW_START', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('progress', models.IntegerField()),
                ('calendar_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEW_START.CalendarPlan')),
            ],
        ),
    ]
